version: '2.4'
services:
  master:
    command: python master.py
    build:
      context: .
    ports:
      - 9999
    volumes:
        - ./:/usr/src/app
    env_file:
        - .env

  slave:
    command: "true"
    image: we-will-lock-queue_master:latest
    depends_on:
      - master

  slave-1:
    command: python slave.py
    image: we-will-lock-queue_slave:latest
    links:
      - master
    volumes:
        - ./:/usr/src/app
    env_file:
        - .env

  slave-2:
    command: python slave.py
    image: we-will-lock-queue_slave:latest
    links:
      - master
    volumes:
        - ./:/usr/src/app
    env_file:
        - .env

  slave-3:
    command: python slave.py
    image: we-will-lock-queue_slave:latest
    links:
      - master
    volumes:
        - ./:/usr/src/app
    env_file:
        - .env



